# Generated by Django 5.1.1 on 2024-11-26 01:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('size', models.IntegerField(default=0)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('mimetype', models.CharField(blank=True, max_length=100, null=True)),
                ('usagecount', models.IntegerField(default=1)),
                ('checksum', models.CharField(blank=True, max_length=100, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('files', models.ManyToManyField(blank=True, to='common.file')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(unique=True)),
                ('files', models.ManyToManyField(blank=True, to='common.file')),
                ('tags', models.ManyToManyField(blank=True, to='common.tag')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField()),
                ('value', models.TextField(blank=True, null=True)),
                ('files', models.ManyToManyField(blank=True, to='common.file')),
                ('tags', models.ManyToManyField(blank=True, to='common.tag')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='file',
            name='tags',
            field=models.ManyToManyField(blank=True, to='common.tag'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['created_at'], name='common_tag_created_bc5d14_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['-created_at'], name='common_tag_created_92197a_idx'),
        ),
        migrations.AddIndex(
            model_name='setting',
            index=models.Index(fields=['created_at'], name='common_sett_created_ff86d2_idx'),
        ),
        migrations.AddIndex(
            model_name='setting',
            index=models.Index(fields=['-created_at'], name='common_sett_created_745ffc_idx'),
        ),
    ]
