# Generated by Django 5.1.1 on 2024-11-26 01:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, editable=False, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, editable=False, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, editable=False, max_length=200, unique=True),
        ),
    ]
