# Generated by Django 5.1.1 on 2024-11-26 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_file_slug_alter_setting_slug_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
