# Generated by Django 5.1.4 on 2024-12-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timbrel', '0002_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaymentmethod',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'cash'), ('card', 'card'), ('bank-transfer', 'bank-transfer'), ('paypal', 'paypal'), ('mpesa', 'mpesa')], default='cash'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'cash'), ('card', 'card'), ('bank-transfer', 'bank-transfer'), ('paypal', 'paypal'), ('mpesa', 'mpesa')], default='cash'),
        ),
    ]
