# Generated by Django 5.1.1 on 2024-11-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_historicalfile_historicalsetting_historicaltag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(default='DEFAULT NAME', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalfile',
            name='name',
            field=models.CharField(default='DEFAULT NAME', max_length=200),
            preserve_default=False,
        ),
    ]
