# Generated by Django 5.1.1 on 2024-12-09 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_facet_facetvalue_historicalfacet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facetvalue',
            name='facet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facet_values', to='common.facet'),
        ),
    ]
