# Generated by Django 5.1.1 on 2024-12-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_facetvalue_facet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facet',
            name='files',
        ),
        migrations.RemoveField(
            model_name='facetvalue',
            name='files',
        ),
        migrations.RemoveField(
            model_name='facetvalue',
            name='tags',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='facet_values',
            field=models.ManyToManyField(blank=True, to='common.facetvalue'),
        ),
        migrations.AddField(
            model_name='file',
            name='facet_values',
            field=models.ManyToManyField(blank=True, to='common.facetvalue'),
        ),
        migrations.AddField(
            model_name='setting',
            name='facet_values',
            field=models.ManyToManyField(blank=True, to='common.facetvalue'),
        ),
        migrations.AddField(
            model_name='tag',
            name='facet_values',
            field=models.ManyToManyField(blank=True, to='common.facetvalue'),
        ),
    ]
