# Generated by Django 5.1.1 on 2024-12-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_remove_facet_files_remove_facetvalue_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facetvalue',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='historicalfacetvalue',
            name='name',
            field=models.CharField(),
        ),
    ]
