# Generated by Django 5.1.1 on 2024-12-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_article_articleimage_articletext_historicalarticle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facetvalue',
            name='tags',
            field=models.ManyToManyField(blank=True, to='common.tag'),
        ),
    ]
